FROM nginx
LABEL version="1.0.0" service="Docker:nginx" objective="Nginx Website"

# atualiza OS basico
RUN apt-get update -y
RUN apt-get install -y softwatre-properties-common

# install Certbot
RUN add-apt-repository ppa:certbot/Certbot
RUN apt-get update -y
RUN apt-get install -y certbot python-certbot-nginx

# deamon mode off
RUN echo "\ndaemon off;" >> /etc/nginx.conf
RUN chown -R www-data:www-data /var/lib/nginx

# importa páginas do site e config do servidor
COPY ./wwwroot/ /usr/share/nginx/html/
COPY ./ConfServer/default.conf /etc/nginx/conf.d/default.conf

# expose 80 and 443 ports
EXPOSE 80
EXPOSE 443

# add nginx staging config
ADD config/climguards-staging.com /etc/nginx/sites-available/climguards.com

# create symlinks
RUN ln -s /etc/nginx/sites-available/climguards.com /etc/nginx/sites-enabled/climguards


WORKDIR /usr/share/nginx/html
ENTRYPOINT [ "/usr/sbin/nginx"]
CMD [ "-g", "daemon off;" ]
