mysql-server-1:
  env_file:
    - ./environment/mysql-server.env
  image: mysql/mysql-server:latest
  ports:
    - "3301:3306"
  command:
    [
      "mysqld",
      "--server_id=1",
      "--binlog_checksum=NONE",
      "--gtid_mode=ON",
      "--enforce_gtid_consistency=ON",
      "--log_bin",
      "--log_slave_updates=ON",
      "--master_info_repository=TABLE",
      "--relay_log_info_repository=TABLE",
      "--transaction_write_set_extraction=XXHASH64",
      "--user=mysql",
      "--mysql_root_password=Xx555W2020",
      "--skip-host-cache",
      "--skip-name-resolve"
    ]

mysql-server-2:
  env_file:
    - ./environment/mysql-server.env
  image: mysql/mysql-server:latest
  ports:
    - "3302:3306"
  command:
    [
      "mysqld",
      "--server_id=2",
      "--binlog_checksum=NONE",
      "--gtid_mode=ON",
      "--enforce_gtid_consistency=ON",
      "--log_bin",
      "--log_slave_updates=ON",
      "--master_info_repository=TABLE",
      "--relay_log_info_repository=TABLE",
      "--transaction_write_set_extraction=XXHASH64",
      "--user=mysql",
      "--mysql_root_password=Xx555W2020",
      "--skip-host-cache",
      "--skip-name-resolve"
    ]

mysql-server-3:
  env_file:
    - ./environment/mysql-server.env
  image: mysql/mysql-server:latest
  ports:
    - "3303:3306"
  command:
    [
      "mysqld",
      "--server_id=3",
      "--binlog_checksum=NONE",
      "--gtid_mode=ON",
      "--enforce_gtid_consistency=ON",
      "--log_bin",
      "--log_slave_updates=ON",
      "--master_info_repository=TABLE",
      "--relay_log_info_repository=TABLE",
      "--transaction_write_set_extraction=XXHASH64",
      "--user=mysql",
      "--mysql_root_password=Xx555W2020",
      "--skip-host-cache",
      "--skip-name-resolve"
    ]

mysql-shell:
  env_file:
    - environment/mysql-server.env
  image: environment/mysql-router/dockefile
  volumes:
      - ./mysql-shell/scripts/:/scripts/
  depends_on:
    - mysql-server-1
    - mysql-server-2
    - mysql-server-3