FROM nginx
LABEL version="1.0.0" service="Docker:nginx" objective="Deploy nginx Website"

COPY ./wwwroot/index.html /usr/share/ngix/html

EXPOSE 80
EXPOSE 800

WORKDIR /usr/share/ngix/html
ENTRYPOINT [ "/usr/sbin/nginx"]
CMD [ "-g", "daemon off" ]
