# AMBIENTE DO SITE HEBER

#Criar Banco de Dados MySQL   - 01. (BACK)  MySQL

#Criar Servico .NET           - 02. (BACK)  .NET Core

#Criar API Node               - 03. (BACK)  API NodeJS

#Criar Servico de mensageria  - 04. (BACK)  Kafka

#Criar API Front NodeJS       - 05. (FRONT) API

#Criar WebServer Nginx        - 06. (FRONT) Nginx
version: '1'
services:

  WebServer1:
    build: 
      dockerfile: ./06. (FRONT) Nginx/Nginx/dockerfile
      context: .
      container_name: "API"
      ports:
      - 80:80
      - 443:443
      restart: always

  