version: '1'
services:

  WebServer1:
    build: 
      dockerfile: ./nginx/dockerfile
      context: .
      container_name: "WebServer"
      ports:
      - 80:80
      - 443:443
      restart: always
    